/**
 * sfx.ts — the Open Game SFX library, as an MCP-side capability.
 *
 * WHY THIS FILE EXISTS
 * --------------------
 * A mod or a map that has no sound feels dead: a door that opens silently, a
 * button that does not click, a pickup with no chime. Hand-authoring audio is
 * not something an agent can do at all, so the only useful thing to give it is
 * a curated, licence-clean catalogue plus a way to prove what it downloaded.
 *
 * The loop mirrors the 3D asset library deliberately:
 *
 *     search -> inspect -> fetch -> VERIFY -> install -> playsound
 *
 * One small file answers everything: `index.json` (~2.5 MB, fetched once and
 * cached on disk) carries, per sound, its category, tags, use cases, mood,
 * bilingual keywords (EN + AR), duration, every available format with its size
 * and SHA-256, and the upstream source. So an agent can choose and verify
 * without pulling 72 MB of audio.
 *
 * THE CATALOGUE GROWS. The upstream repository is updated continuously, so
 * nothing here may hardcode a count, a pack list or a category list — every
 * one of those is read from the catalogue at call time.
 *
 * A note on the upstream URLs: some entries carry raw spaces and brackets in
 * their path (the OGA packs). Those URLs are not fetchable as written, so every
 * download goes through `encodeUrl()` below. This is defensive on purpose — the
 * catalogue is generated by a script we do not control, and a broken link must
 * not turn into a silent failure for the agent.
 */
import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { config } from "./config.js";

/** One catalogue row. Every field is optional-tolerant: the schema may grow. */
export interface SfxSound {
  id: string;
  title: string;
  pack: string;
  category: string;
  tags?: string[];
  use_cases?: string[];
  mood?: string[];
  keywords_en?: string[];
  keywords_ar?: string[];
  duration_sec?: number;
  formats?: string[];
  file_ogg?: string | null;
  file_mp3?: string | null;
  file_wav?: string | null;
  file_flac?: string | null;
  download_url_ogg?: string | null;
  download_url_mp3?: string | null;
  download_url_wav?: string | null;
  download_url_flac?: string | null;
  size_ogg?: number | null;
  size_mp3?: number | null;
  size_wav?: number | null;
  size_flac?: number | null;
  sha256_ogg?: string | null;
  sha256_mp3?: string | null;
  sha256_wav?: string | null;
  sha256_flac?: string | null;
  license?: string;
  source?: string;
}

export interface SfxCatalog {
  version?: string;
  repo?: string;
  generated_at?: string;
  license_audio?: string;
  count?: number;
  batches?: string[];
  sounds: SfxSound[];
}

export class SfxLibraryError extends Error {
  constructor(message: string, readonly hint?: string) {
    super(message);
    this.name = "SfxLibraryError";
  }
}

/** Formats the engine accepts under `assets/<ns>/sounds/` (ModManager allowlist). */
export const ENGINE_FORMATS = ["ogg", "wav", "mp3", "flac"] as const;
export type SfxFormat = (typeof ENGINE_FORMATS)[number];

/** OGG first: smallest for the same quality, and what Minecraft itself ships. */
export const FORMAT_PREFERENCE: SfxFormat[] = ["ogg", "mp3", "wav", "flac"];

// ---------------------------------------------------------------------
// URLs
// ---------------------------------------------------------------------

/**
 * Percent-encode the path of a URL without touching the scheme, host or query.
 *
 * The upstream catalogue contains entries whose path has literal spaces and
 * brackets (e.g. `…/The Essential Retro … Collection [512 sounds] By …/x.wav`).
 * Node's fetch rejects those outright with `InvalidURL`, so an agent that used
 * the documented field verbatim would fail on 92% of the WAV entries. Encoding
 * here means the field is usable no matter how it was generated.
 */
export function encodeUrl(raw: string): string {
  try {
    const u = new URL(raw);
    u.pathname = u.pathname
      .split("/")
      .map((seg) => encodeURIComponent(decodeURIComponent(seg)))
      .join("/");
    return u.toString();
  } catch {
    // Not parseable as a URL (relative path) — encode the segments by hand.
    return raw
      .split("/")
      .map((seg) => {
        try {
          return encodeURIComponent(decodeURIComponent(seg));
        } catch {
          return encodeURIComponent(seg);
        }
      })
      .join("/");
  }
}

function rawBase(): string {
  const url = config.sfxRepoUrl;
  if (!url) {
    throw new SfxLibraryError(
      "The sound library is unlinked.",
      "Set OMNIMOD_SFX_REPO (or pass a repo URL to omni_config) to re-link it.",
    );
  }
  const m = /^https?:\/\/(?:www\.)?github\.com\/([^/]+)\/([^/#?]+)/i.exec(url);
  if (m) {
    const repo = m[2].replace(/\.git$/i, "");
    return `https://raw.githubusercontent.com/${m[1]}/${repo}/HEAD`;
  }
  return url.replace(/\/+$/, "");
}

function localRoot(): string | null {
  const p = config.sfxLocalPath;
  return p ? resolve(p) : null;
}

export function librarySource(): string {
  const local = localRoot();
  if (local) return `local checkout: ${local}`;
  return `HTTPS mirror: ${rawBase()}`;
}

function catalogCachePath(): string {
  return join(config.sfxCacheDir, "index.json");
}

async function readText(rel: string): Promise<string> {
  const local = localRoot();
  if (local) return readFile(join(local, ...rel.split("/")), "utf8");
  const url = `${rawBase()}/${rel}`;
  const res = await fetch(url, { redirect: "follow" });
  if (!res.ok) {
    throw new SfxLibraryError(
      `GET ${url} -> HTTP ${res.status}`,
      res.status === 404
        ? "The library layout may have changed; re-check that index.json exists in the repository."
        : "Check network access, or set OMNIMOD_SFX_LOCAL_PATH to a local clone to work offline.",
    );
  }
  return res.text();
}

// ---------------------------------------------------------------------
// Catalogue: lazy, cached, disk-backed, staleness-aware
// ---------------------------------------------------------------------

let cached: SfxCatalog | null = null;

function catalogIsUsable(c: unknown): c is SfxCatalog {
  if (!c || typeof c !== "object") return false;
  const cat = c as SfxCatalog;
  if (!Array.isArray(cat.sounds) || cat.sounds.length === 0) return false;
  const first = cat.sounds[0] as Partial<SfxSound>;
  return typeof first.id === "string" && typeof first.pack === "string";
}

export async function loadCatalog(opts: { refresh?: boolean } = {}): Promise<SfxCatalog> {
  if (cached && !opts.refresh) return cached;

  const cacheFile = catalogCachePath();
  if (!opts.refresh) {
    try {
      const raw = await readFile(cacheFile, "utf8");
      const parsed: unknown = JSON.parse(raw);
      if (catalogIsUsable(parsed)) {
        cached = parsed;
        return cached;
      }
    } catch {
      /* no usable cache — fetch */
    }
  }

  const text = await readText("index.json");
  const parsed: unknown = JSON.parse(text);
  if (!catalogIsUsable(parsed)) {
    throw new SfxLibraryError(
      "index.json did not parse into a usable sound list.",
      "Re-run the library build, or point OMNIMOD_SFX_REPO at the correct repository.",
    );
  }
  cached = parsed;
  try {
    await mkdir(dirname(cacheFile), { recursive: true });
    await writeFile(cacheFile, text, "utf8");
  } catch {
    /* a read-only cache dir must never break a search */
  }
  return parsed;
}

/** Exposed for the selfcheck battery. */
export function catalogIsValid(c: unknown): boolean {
  return catalogIsUsable(c);
}

export function catalogIsWarm(): boolean {
  return cached !== null;
}

// ---------------------------------------------------------------------
// Search
// ---------------------------------------------------------------------

export interface SfxFilters {
  query?: string;
  category?: string;
  pack?: string;
  tag?: string[];
  useCase?: string;
  mood?: string;
  minDuration?: number;
  maxDuration?: number;
  format?: string;
  limit?: number;
}

function haystack(s: SfxSound): string {
  return [
    s.id, s.title, s.pack, s.category,
    ...(s.tags ?? []),
    ...(s.use_cases ?? []),
    ...(s.mood ?? []),
    ...(s.keywords_en ?? []),
    ...(s.keywords_ar ?? []),
  ]
    .join(" ")
    .toLowerCase();
}

/**
 * Arabic -> English bridge.
 *
 * The upstream catalogue carries Arabic keywords on every entry, but the whole
 * vocabulary is only ~47 distinct words (التقاط، ضربة، واجهة، فوز …). So an
 * Arabic-speaking user asking for "سيف" or "باب" or "خطوات" gets nothing, even
 * though the English catalogue has swords, doors and footsteps. This maps the
 * concepts an Arabic request actually uses onto the English terms the catalogue
 * does carry. It is a bridge, not a translation layer: every mapped term is
 * searched in ADDITION to the original, so a term that is already present is
 * never lost.
 */
const AR_SYNONYMS: Record<string, string[]> = {
  "زر": ["button", "click", "ui"],
  "ازرار": ["button", "click", "ui"],
  "أزرار": ["button", "click", "ui"],
  "نقرة": ["click", "tap"],
  "ضغطة": ["click", "press"],
  "واجهة": ["ui", "interface", "menu"],
  "قائمة": ["menu", "interface"],
  "تأكيد": ["confirm", "select"],
  "خطأ": ["error", "negative"],
  "تنبيه": ["alert", "notification"],
  "تمرير": ["scroll"],
  "تبديل": ["switch", "toggle"],
  "سيف": ["sword", "blade"],
  "سيوف": ["sword", "blade"],
  "ضربة": ["hit", "impact", "punch"],
  "ضربات": ["hit", "impact", "punch"],
  "اصطدام": ["impact", "crash", "collision"],
  "تحطم": ["crash", "break", "smash"],
  "انفجار": ["explosion", "boom", "blast"],
  "رصاصة": ["shot", "gun", "bullet"],
  "بندقية": ["gun", "rifle", "shot"],
  "قوس": ["bow", "arrow"],
  "سهم": ["arrow"],
  "درع": ["shield"],
  "معركة": ["battle", "combat", "fight"],
  "قفز": ["jump"],
  "خطوة": ["footstep", "step", "walk"],
  "خطوات": ["footstep", "step", "walk"],
  "مشي": ["walk", "footstep"],
  "جري": ["run", "sprint"],
  "هبوط": ["land", "impact"],
  "التقاط": ["pickup", "collect", "get"],
  "عملة": ["coin", "money"],
  "عملات": ["coin", "money"],
  "مفتاح": ["key", "unlock"],
  "باب": ["door"],
  "أبواب": ["door"],
  "صندوق": ["chest", "crate", "box"],
  "كنز": ["treasure", "chest"],
  "جرس": ["bell"],
  "فوز": ["win", "success", "victory"],
  "خسارة": ["lose", "fail", "defeat"],
  "موسيقى": ["music", "jingle"],
  "نغمة": ["jingle", "tone", "chime"],
  "صوت": ["sound", "voice"],
  "أصوات": ["sound", "voice"],
  "وحش": ["monster", "zombie", "creature"],
  "زومبي": ["zombie"],
  "شبح": ["ghost", "spooky"],
  "صراخ": ["scream", "scream", "yell"],
  "بكاء": ["cry", "scream"],
  "ريترو": ["retro", "8-bit", "arcade"],
  "أركيد": ["arcade", "retro"],
  "ليزر": ["laser", "sci-fi"],
  "فضاء": ["space", "sci-fi"],
  "صاروخ": ["rocket", "missile"],
  "محرك": ["engine", "machine"],
  "آلة": ["machine", "engine"],
  "ماء": ["water", "splash"],
  "مطر": ["rain", "weather"],
  "ريح": ["wind", "weather"],
  "طائر": ["bird"],
  "حيوان": ["animal"],
  "قهوة": ["coffee", "cafe"],
  "طعام": ["food", "eat"],
  "مطعم": ["restaurant", "food"],
  "ورق": ["card"],
  "نرد": ["dice"],
  "كازينو": ["casino"],
  "ماكينة": ["slot", "machine", "casino"],
};

/** Expand a query term into every term worth searching for it. */
export function expandTerms(term: string): string[] {
  const t = term.trim().toLowerCase();
  if (!t) return [];
  const out = new Set<string>([t]);
  for (const extra of AR_SYNONYMS[t] ?? []) out.add(extra);
  return [...out];
}

/** Identity hits (title/id/pack) outrank tag or category hits. */
function score(s: SfxSound, terms: string[]): number {
  const ident = `${s.id} ${s.title}`.toLowerCase();
  const cat = `${s.category} ${s.pack}`.toLowerCase();
  const kw = `${(s.tags ?? []).join(" ")} ${(s.use_cases ?? []).join(" ")} ${(s.mood ?? []).join(" ")}`.toLowerCase();
  const ar = (s.keywords_ar ?? []).join(" ").toLowerCase();
  let n = 0;
  for (const t of terms) {
    // A direct hit in the sound's own Arabic keywords is the strongest signal
    // an Arabic request can produce, so it outranks a synonym match.
    if (ar.includes(t)) n += 8;
    // Latin terms must match at a word boundary. Without this, "win" (from the
    // Arabic "فوز") scores a full identity hit on "swing3" and buries the real
    // win/lose jingles under a pile of weapon swings.
    if (/^[a-z0-9]+$/.test(t)) {
      if (new RegExp(`\\b${t.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}`).test(ident)) n += 10;
      else if (ident.includes(t)) n += 3;
      if (new RegExp(`\\b${t}`).test(cat)) n += 4;
      if (new RegExp(`\\b${t}`).test(kw)) n += 3;
    } else {
      if (ident.includes(t)) n += 10;
      if (cat.includes(t)) n += 4;
      if (kw.includes(t)) n += 3;
    }
  }
  return n;
}

export function searchSfx(cat: SfxCatalog, f: SfxFilters): SfxSound[] {
  const out: SfxSound[] = [];
  for (const s of cat.sounds) {
    if (f.category && s.category !== f.category) continue;
    if (f.pack && s.pack !== f.pack) continue;
    if (f.format && !(s.formats ?? []).includes(f.format)) continue;
    if (f.tag && f.tag.length > 0 && !f.tag.every((t) => (s.tags ?? []).includes(t))) continue;
    if (f.useCase) {
      const uc = (s.use_cases ?? []).join(" ").toLowerCase();
      if (!uc.includes(f.useCase.toLowerCase())) continue;
    }
    if (f.mood) {
      const md = (s.mood ?? []).join(" ").toLowerCase();
      if (!md.includes(f.mood.toLowerCase())) continue;
    }
    if (f.minDuration !== undefined && (s.duration_sec ?? 0) < f.minDuration) continue;
    if (f.maxDuration !== undefined && (s.duration_sec ?? 0) > f.maxDuration) continue;
    out.push(s);
  }

  const rawTerms = (f.query ?? "")
    .toLowerCase()
    .split(/[\s,]+/)
    .filter((t) => t.length > 0);
  // Arabic terms are expanded into the English vocabulary the catalogue carries,
  // in ADDITION to themselves, so a request in Arabic can actually land.
  const terms = [...new Set(rawTerms.flatMap(expandTerms))];

  if (terms.length > 0) {
    const scored: Array<{ n: number; s: SfxSound }> = [];
    for (const s of out) {
      const n = score(s, terms);
      if (n > 0) scored.push({ n, s });
    }
    // Relevance, then shortest first: a 0.1 s click usually beats an 8 s bed.
    scored.sort(
      (a, b) =>
        b.n - a.n ||
        (a.s.duration_sec ?? 0) - (b.s.duration_sec ?? 0) ||
        a.s.id.localeCompare(b.s.id),
    );
    return scored.map((x) => x.s);
  }

  out.sort(
    (a, b) =>
      a.category.localeCompare(b.category) ||
      (a.duration_sec ?? 0) - (b.duration_sec ?? 0) ||
      a.id.localeCompare(b.id),
  );
  return out;
}

export function findSfx(cat: SfxCatalog, id: string): SfxSound | null {
  const want = id.trim();
  for (const s of cat.sounds) if (s.id === want) return s;
  const hits = cat.sounds.filter((s) => s.title === want || s.id.endsWith(`_${want}`));
  return hits.length === 1 ? hits[0] : null;
}

export function findSfxCandidates(cat: SfxCatalog, id: string, limit = 12): SfxSound[] {
  const want = id.trim();
  const exact = cat.sounds.filter((s) => s.id === want);
  if (exact.length > 0) return exact;
  return cat.sounds.filter((s) => s.title === want || s.id.endsWith(`_${want}`)).slice(0, limit);
}

/** The compact row an agent sees. */
export function project(s: SfxSound) {
  return {
    id: s.id,
    title: s.title,
    category: s.category,
    pack: s.pack,
    seconds: s.duration_sec ?? null,
    formats: s.formats ?? [],
    tags: s.tags ?? [],
    useCases: s.use_cases ?? [],
    mood: s.mood ?? [],
    keywordsAr: s.keywords_ar ?? [],
  };
}

/** Which formats this sound can actually be downloaded in. */
export function availableFormats(s: SfxSound): SfxFormat[] {
  return FORMAT_PREFERENCE.filter((f) => {
    const url = (s as unknown as Record<string, unknown>)[`download_url_${f}`];
    return typeof url === "string" && url.length > 0;
  });
}

/** Pick the best format the caller allows, preferring OGG. */
export function chooseFormat(s: SfxSound, wanted?: string): SfxFormat {
  const have = availableFormats(s);
  if (have.length === 0) {
    throw new SfxLibraryError(
      `"${s.id}" has no downloadable format in the catalogue.`,
      "The catalogue entry may be incomplete — try omni_sfx_search for another sound.",
    );
  }
  if (wanted) {
    const w = wanted.toLowerCase() as SfxFormat;
    if (!have.includes(w)) {
      throw new SfxLibraryError(
        `"${s.id}" is not available as ${w}.`,
        `Available: ${have.join(", ")}. Omit 'format' to take the best one automatically.`,
      );
    }
    return w;
  }
  return have[0];
}

// ---------------------------------------------------------------------
// Honest analysis of a catalogue entry
// ---------------------------------------------------------------------

/** What a duration is actually good for — the question an agent really asks. */
export function durationRole(sec: number): string {
  if (sec <= 0.15) return "instant tick / hover blip";
  if (sec <= 0.6) return "one-shot UI click or pickup";
  if (sec <= 1.5) return "one-shot impact, footstep, short vocal";
  if (sec <= 4) return "short stinger / weapon / short ambience";
  if (sec <= 12) return "jingle, music sting, looping ambience bed";
  return "music / long ambience — check it is not too long for a one-shot trigger";
}

export function assessSfx(s: SfxSound, need?: string) {
  const have = availableFormats(s);
  const sec = s.duration_sec ?? 0;
  const size = (s as unknown as Record<string, number | null>)[`size_${have[0]}`] ?? null;
  // Below ~0.5 s the container header dominates the byte count, so a derived
  // "bitrate" would be meaningless noise (a 0.03 s click reports ~1100 kbps).
  const bitrate = size && sec >= 0.5 ? Math.round((size * 8) / sec / 1000) : null;

  const notes: string[] = [];
  notes.push(`duration ${sec.toFixed(2)} s — ${durationRole(sec)}`);
  if (have.length === 0) notes.push("NO downloadable format in the catalogue — do not use");
  else notes.push(`downloadable as ${have.join(", ")} (OGG preferred: smallest at equal quality)`);
  if (bitrate) notes.push(`~${bitrate} kbps at the preferred format`);
  if (sec > 12) notes.push("long: do not fire this on a repeated event (a per-tick trigger would spam it)");

  const warnings: string[] = [];
  const n = (need ?? "").toLowerCase();
  if (n) {
    // NOTE: no trailing \b on these — the words appear inflected in real
    // requests ("looping ambience", "footsteps", "clicks"), and a trailing
    // boundary silently stops matching the very phrasing it exists to catch.
    const wantsLoop = /\b(ambien|loop|background|music|continuous|wind|rain|machine hum|atmospher)/.test(n);
    const wantsOneShot =
      /\b(click|button|press|tap|hit|impact|step|footstep|pickup|collect|coin|shoot|fire|open|close|jump|land|hurt|explos|break|craft|equip)/.test(n);
    if (wantsOneShot && sec > 6) {
      warnings.push(
        `You described a one-shot trigger, but this sound is ${sec.toFixed(1)} s long — a ${durationRole(sec)} will overrun the action.`,
      );
    }
    if (wantsLoop && sec < 1) {
      warnings.push(
        `You described ambience/looping, but this sound is only ${sec.toFixed(2)} s — it will sound like a click on repeat.`,
      );
    }
    if (/\b(ui|interface|menu|button|click)\b/.test(n) && !/ui|interface|gui/.test(`${s.category} ${s.pack}`)) {
      warnings.push(
        `You asked for a UI sound but this one lives in "${s.category}" — check the UI categories before settling.`,
      );
    }
  }

  return {
    seconds: sec,
    durationRole: durationRole(sec),
    formats: have,
    preferredFormat: have[0] ?? null,
    sizeBytesPreferred: size,
    approxKbps: bitrate,
    licence: s.license ?? "CC0-1.0",
    upstream: s.source ?? null,
    notes,
    mismatchWarnings: warnings,
  };
}

// ---------------------------------------------------------------------
// Audio header probe — real numbers from the real bytes
// ---------------------------------------------------------------------

export interface AudioHeader {
  container: string;
  channels: number | null;
  sampleRate: number | null;
  bitsPerSample: number | null;
  /** True when the bytes were recognised at all. */
  recognised: boolean;
}

/**
 * Read the technical header of an audio file WITHOUT decoding it.
 *
 * This is the "analyse the sound" part: sample rate and channel count decide
 * whether a sound will sit correctly in a mix, and a mono 22050 Hz file dropped
 * next to stereo 44100 Hz material is audible. Parsing the header costs a few
 * hundred bytes instead of a full decode.
 */
export function probeAudioHeader(buf: Buffer): AudioHeader {
  const none: AudioHeader = { container: "unknown", channels: null, sampleRate: null, bitsPerSample: null, recognised: false };
  if (buf.length < 16) return none;

  // OGG / Vorbis — the identification header packet starts with \x01vorbis,
  // followed by version(4) channels(1) sampleRate(4) ...
  if (buf.subarray(0, 4).toString("latin1") === "OggS") {
    const i = buf.indexOf(Buffer.from([0x01, 0x76, 0x6f, 0x72, 0x62, 0x69, 0x73]));
    if (i > 0 && i + 16 <= buf.length) {
      return {
        container: "ogg/vorbis",
        channels: buf.readUInt8(i + 11),
        sampleRate: buf.readUInt32LE(i + 12),
        bitsPerSample: null,
        recognised: true,
      };
    }
    return { ...none, container: "ogg", recognised: true };
  }

  // WAV / RIFF — "fmt " chunk: format(2) channels(2) sampleRate(4) ... bits(2)
  if (buf.subarray(0, 4).toString("latin1") === "RIFF" && buf.subarray(8, 12).toString("latin1") === "WAVE") {
    const i = buf.indexOf("fmt ", 0, "latin1");
    if (i >= 0 && i + 24 <= buf.length) {
      return {
        container: "wav",
        channels: buf.readUInt16LE(i + 10),
        sampleRate: buf.readUInt32LE(i + 12),
        bitsPerSample: buf.readUInt16LE(i + 22),
        recognised: true,
      };
    }
    return { ...none, container: "wav", recognised: true };
  }

  // FLAC — "fLaC" + 4-byte metadata block header, then the 34-byte STREAMINFO
  // body. The packed sampleRate/channels/bits field sits 10 bytes into the body.
  if (buf.subarray(0, 4).toString("latin1") === "fLaC") {
    const body = 8; // 4 magic + 4 block header (the type name is NOT in the file)
    if (body + 18 <= buf.length) {
      const v = buf.readBigUInt64BE(body + 10);
      return {
        container: "flac",
        channels: Number((v >> 41n) & 7n) + 1,
        sampleRate: Number((v >> 44n) & 0xfffffn),
        bitsPerSample: Number((v >> 36n) & 0x1fn) + 1,
        recognised: true,
      };
    }
    return { ...none, container: "flac", recognised: true };
  }

  // MP3 — frame sync, skipping an ID3v2 tag when present
  let off = 0;
  if (buf.subarray(0, 3).toString("latin1") === "ID3" && buf.length > 10) {
    const size = ((buf[6] & 0x7f) << 21) | ((buf[7] & 0x7f) << 14) | ((buf[8] & 0x7f) << 7) | (buf[9] & 0x7f);
    off = 10 + size;
  }
  if (off + 4 <= buf.length && buf[off] === 0xff && (buf[off + 1] & 0xe0) === 0xe0) {
    const h = buf.readUInt32BE(off);
    const srIdx = (h >> 10) & 3;
    const rates = [44100, 48000, 32000, 0];
    return {
      container: "mp3",
      channels: ((h >> 6) & 3) === 3 ? 1 : 2,
      sampleRate: srIdx === 3 ? null : rates[srIdx],
      bitsPerSample: null,
      recognised: true,
    };
  }

  return none;
}

// ---------------------------------------------------------------------
// Fetch
// ---------------------------------------------------------------------

export interface FetchedSfx {
  id: string;
  format: SfxFormat;
  path: string;
  bytes: number;
  verified: boolean;
  sha256: string;
  expectedSha256: string | null;
  header: AudioHeader;
  note: string;
}

function sha256(buf: Buffer): string {
  return createHash("sha256").update(buf).digest("hex");
}

export async function fetchSfx(
  s: SfxSound,
  destDir: string,
  opts: { format?: string; fileName?: string } = {},
): Promise<FetchedSfx> {
  const fmt = chooseFormat(s, opts.format);
  const url = (s as unknown as Record<string, string | null>)[`download_url_${fmt}`];
  if (!url) {
    throw new SfxLibraryError(`"${s.id}" has no ${fmt} download URL.`);
  }
  const res = await fetch(encodeUrl(url), { redirect: "follow" });
  if (!res.ok) {
    throw new SfxLibraryError(
      `GET ${fmt} for "${s.id}" -> HTTP ${res.status}`,
      "The upstream file may have moved. Try another format, or another sound.",
    );
  }
  const buf = Buffer.from(await res.arrayBuffer());
  const leaf = opts.fileName ?? `${s.id.replace(/[^A-Za-z0-9_-]/g, "_")}.${fmt}`;
  await mkdir(destDir, { recursive: true });
  const path = join(destDir, leaf);
  await writeFile(path, buf);

  const expected = (s as unknown as Record<string, string | null>)[`sha256_${fmt}`] ?? null;
  const actual = sha256(buf);
  const verified = expected !== null && expected === actual;

  return {
    id: s.id,
    format: fmt,
    path,
    bytes: buf.length,
    verified,
    sha256: actual,
    expectedSha256: expected,
    header: probeAudioHeader(buf),
    note:
      expected === null
        ? "The catalogue records no SHA-256 for this format, so the download could not be verified."
        : verified
          ? "SHA-256 matches the catalogue: this is byte-identical to the indexed file."
          : "SHA-256 MISMATCH — the file differs from the catalogue entry.",
  };
}

// ---------------------------------------------------------------------
// Reporting
// ---------------------------------------------------------------------

export function librarySummary(cat: SfxCatalog) {
  const byCategory = new Map<string, number>();
  const byPack = new Map<string, number>();
  const byFormat = new Map<string, number>();
  let totalSec = 0;
  for (const s of cat.sounds) {
    byCategory.set(s.category, (byCategory.get(s.category) ?? 0) + 1);
    byPack.set(s.pack, (byPack.get(s.pack) ?? 0) + 1);
    for (const f of s.formats ?? []) byFormat.set(f, (byFormat.get(f) ?? 0) + 1);
    totalSec += s.duration_sec ?? 0;
  }
  return {
    sounds: cat.sounds.length,
    packs: byPack.size,
    categories: Object.fromEntries([...byCategory.entries()].sort((a, b) => b[1] - a[1])),
    formats: Object.fromEntries(byFormat),
    totalAudioSeconds: Math.round(totalSec),
    catalogueVersion: cat.version ?? "unknown",
    generatedAt: cat.generated_at ?? "unknown",
    licence: cat.license_audio ?? "CC0-1.0",
    note: "The upstream repository is updated continuously — counts and packs are read live, never hardcoded.",
    source: librarySource(),
  };
}

// ---------------------------------------------------------------------
// sounds.json — the event definition a sound needs to be reachable
// ---------------------------------------------------------------------

export interface SoundsJsonMerge {
  text: string;
  /** True when the EVENT key did not exist before and was created. */
  eventCreated: boolean;
  /** True when the sound entry was appended to the event's sounds array. */
  soundAdded: boolean;
  event: string;
  /** How many entries the event has after the merge. */
  existingSounds: number;
}

/**
 * Merge one sound into a `sounds.json` document, preserving everything else.
 *
 * The 1.8 handler registers every top-level key of `assets/<ns>/sounds.json` as
 * the event `<ns>:<key>`, and resolves each entry of that event's `sounds` array
 * to `assets/<ns>/sounds/<entry>.ogg`. So the file on disk MUST be named
 * `<entry>.ogg`, and the entry must be listed under the event you will play.
 *
 * A malformed existing document is reported rather than silently replaced — an
 * agent that overwrote a pack's sounds.json would break every other sound in it.
 */
export function mergeSoundsJson(
  existingText: string | null,
  event: string,
  soundName: string,
  opts: { category?: string; subtitle?: string } = {},
): SoundsJsonMerge {
  let doc: Record<string, unknown> = {};
  if (existingText && existingText.trim().length > 0) {
    let parsed: unknown;
    try {
      parsed = JSON.parse(existingText);
    } catch (e) {
      throw new SfxLibraryError(
        "The existing sounds.json is not valid JSON.",
        `Refusing to overwrite it (that would break every other sound in the pack). Parser said: ${(e as Error).message}`,
      );
    }
    if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
      throw new SfxLibraryError(
        "The existing sounds.json is not a JSON object.",
        "Refusing to overwrite it. Repair or remove it first.",
      );
    }
    doc = parsed as Record<string, unknown>;
  }

  const before = Object.prototype.hasOwnProperty.call(doc, event);
  const entry = (before ? doc[event] : undefined) as
    | { sounds?: unknown[]; category?: string; subtitle?: string }
    | undefined;

  if (before && (!entry || typeof entry !== "object" || Array.isArray(entry))) {
    throw new SfxLibraryError(
      `sounds.json already has an entry "${event}" that is not an object.`,
      "Pick a different event name, or repair the existing entry.",
    );
  }

  const target = entry ?? {};
  const list = Array.isArray(target.sounds) ? (target.sounds as unknown[]) : [];
  const already = list.some(
    (x) =>
      x === soundName ||
      (x && typeof x === "object" && (x as { name?: string }).name === soundName),
  );
  if (!already) list.push(soundName);
  target.sounds = list;
  if (opts.category && !target.category) target.category = opts.category;
  if (opts.subtitle && !target.subtitle) target.subtitle = opts.subtitle;
  doc[event] = target;

  return {
    text: JSON.stringify(doc, null, 2) + "\n",
    eventCreated: !before,
    soundAdded: !already,
    event,
    existingSounds: list.length,
  };
}

/** The event name an agent should play for a sound, derived from its id. */
export function defaultEventName(s: SfxSound): string {
  const base = (s.title || s.id.split("_").pop() || s.id)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
  return base.length > 0 ? base : "sfx";
}

/** A safe on-disk base name for the sound file (no extension). */
export function safeSoundBase(s: SfxSound): string {
  const base = s.id.replace(/[^A-Za-z0-9_-]/g, "_").slice(0, 80);
  return base.length > 0 ? base : "sfx";
}

// ---------------------------------------------------------------------
// The engine constraint that decides everything
// ---------------------------------------------------------------------

/**
 * TRUE FACT ABOUT THIS ENGINE, read from the source rather than assumed:
 * `SoundHandler.loadSoundResource` builds every file reference as
 * `"sounds/" + name + ".ogg"` (SoundHandler.java:242) with no extension
 * handling, and `EaglercraftSoundManager` then asks the platform for exactly
 * that path. So a sound referenced from `sounds.json` is only ever reachable
 * when the file on disk is `<name>.ogg`.
 *
 * WAV/MP3/FLAC files are still COPIED into a resource pack (ModManager's
 * audio-asset allowlist accepts them) and the Android backend can decode them —
 * but nothing in the vanilla resolution path ever asks for them, so as a
 * `sounds.json` entry they are dead weight.
 *
 * Consequence for the library: only entries that offer OGG can be installed
 * as-is. Anything else needs an encoder.
 */
export const ENGINE_PLAYABLE_EXTENSION = ".ogg";

/** Encoders we will use, in order, if the chosen sound has no OGG upstream. */
export const ENCODER_CANDIDATES = ["ffmpeg", "oggenc"] as const;

/** Engine-side contract for actually using a sound. */
export const ENGINE_NOTES = {
  playableExtension: ENGINE_PLAYABLE_EXTENSION,
  acceptedOnDisk: ENGINE_FORMATS,
  layout: "assets/<namespace>/sounds/<name>.ogg plus assets/<namespace>/sounds.json",
  playCommand: "playsound <namespace>:<event> <player|@a> [x y z] [volume] [pitch] [minVolume]",
  modPath: "inside a mod folder or JAR: assets/<modid>/sounds/** + assets/<modid>/sounds.json",
  mapPath: "worlds/<map>/mods_folders/<folder>/assets/<ns>/sounds/** — translated into the world resource pack on world load",
  limit: "keep one-shots short; long files are streamed and cost more on a weak device",
  onlyOggIsReachable:
    "sounds.json entries always resolve to <name>.ogg (SoundHandler.java:242), so a WAV/MP3/FLAC file placed in a pack is never requested. Convert to OGG.",
} as const;

